import { useState, useRef, useEffect } from "react";
import { invoke, Channel } from "@tauri-apps/api/core";

function App() {
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState("");
  const [isTyping, setIsTyping] = useState(false);
  const messagesEndRef = useRef(null);
  const inputRef = useRef(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages, isTyping]);

  useEffect(() => {
    inputRef.current?.focus();
  }, []);

  const timeNow = () =>
    new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });

  const handleSend = async () => {
    const text = input.trim();
    if (!text) return;

    const userMessage = {
      id: Date.now(),
      text,
      sender: "user",
      time: timeNow(),
    };
    setMessages((prev) => [...prev, userMessage]);
    setInput("");
    setIsTyping(true);

    const botMessageId = Date.now() + 1;
    setMessages((prev) => [
      ...prev,
      { id: botMessageId, text: "", sender: "bot", time: timeNow() },
    ]);

    // appends the individual tokens generated by LLM to the output
    try {
      const onEvent = new Channel();
      onEvent.onmessage = (token) => {
        setMessages((prev) =>
          prev.map((m) =>
            m.id === botMessageId ? { ...m, text: m.text + token } : m
          )
        );
      };

      // Invokes rust Layer through Tauri's IPC - no HTTP
      await invoke("run_llm", { message: text, onEvent });
    } catch (err) {
      setMessages((prev) =>
        prev.map((m) =>
          m.id === botMessageId
            ? { ...m, text: "Failed to connect to the backend." }
            : m
        )
      );
    } finally {
      setIsTyping(false);
    }
  };

  const handleKeyDown = (e) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  return (
    <div className="chat-container">
      <div className="messages">
        {messages.length === 0 && (
          <div className="empty-state">
            <p>Start a conversation</p>
            <p>Type a message below to begin</p>
          </div>
        )}
        {messages.map((msg) => (
          <div key={msg.id} className={`message ${msg.sender}`}>
            <p>{msg.text}</p>
            <span className="time">{msg.time}</span>
          </div>
        ))}
        {isTyping && <div className="typing-indicator">...</div>}
        <div ref={messagesEndRef} />
      </div>
      <div className="input-area">
        <input
          ref={inputRef}
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={handleKeyDown}
          placeholder="Type your message..."
        />
        <button onClick={handleSend}>Send</button>
      </div>
    </div>
  );
}

export default App;